package com.sample.cleanarch.core.exception

class UserAlreadyExistsException(
) : RuntimeException(
    "User already exists!"
)